from .login import *
from .register import *
from .main import *
from .earthquakes import *
from .flooding import *
from .landslides import *
from .wildfires import *
from .preparation import *
from .emergency_contact import *
from .why import *
from .database import *
from .logout import *
from .text import *